name: Playwright API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    services:
      oracle:
        image: gvenzl/oracle-xe:23-slim
        ports:
          - 1521:1521
        env:
          ORACLE_PASSWORD: root
        options: >-
          --health-cmd="echo 'SELECT 1 FROM DUAL;' | sqlplus -s SYSTEM/root@XE"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Wait for Oracle DB to be ready
        run: |
          echo "Esperando Oracle iniciar..."
          for i in {1..30}; do
            echo "Tentativa $i"
            if echo "SELECT 1 FROM DUAL;" | sqlplus -s SYSTEM/root@//localhost:1521/XE; then
              echo "Oracle está pronto!"
              break
            fi
            sleep 10
          done

      - name: Run API + Playwright tests
        run: |
          node index.js &
          SERVER_PID=$!
          sleep 10 # tempo para o servidor subir
          npx playwright test
          kill $SERVER_PID
