name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      oracle:
        image: gvenzl/oracle-xe:21-slim
        ports:
          - 1521:1521
        options: >-
          --health-cmd "echo 'SELECT 1 FROM dual;' | sqlplus system/root@//localhost:1521/XEPDB1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Wait for Oracle to be ready
        run: sleep 60

      - name: Run API server
        run: node index.js &
        env:
          ORACLE_PASSWORD: root

      - name: Run Playwright tests
        run: npx playwright test
